Workaround for ripemd160 not being available on Google Colab
XRPLF/xrpl-py pull request #273
Opened 2021-07-12 12:51 UTC by hammertoe

## High Level Overview of Change

Use PyCrypto for RIPEMD160 hash if not found in hashlib

### Context of Change

`hashlib` relies upon OpenSSL to provide RIPEMD160. It can occur that OpenSSL is not configured to have RIPEMD160, in particular it is not found in Google Colab. I had a good play around with installing/re-installing OpenSSL and various dependancies on Google Colab, but could not get it to find RIPEMD160. There is an implementation of it in `pycrypto`, and so if we can't find it in hashlib, then try looking in there instead.

### Type of Change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

## Before / After

Moved the check from `__init__.py` into `helpers.py`, define a lambda to abstract the call.

## Test Plan

Manual test and it seems to work ok.

2021-07-13 06:04 UTC, ledhed2222 commented
so - i think this is a great idea, and yes RIPEMD support seems to be an issue on all 3.7.x versions. i'd love to work around this with another library like you've done! if we do this, i think we should commit to it for all versions and try either the added library or the `hashlib` version. if you do that, you'll need to add a runtime dependency to this library by running `poetry add <library>` to add to dependencies.

2021-07-18 23:14 UTC, ledhed2222 requested changes
see comments :)

2022-12-12 22:51 UTC, connorjchen commented
Updated version of PR: https://github.com/XRPLF/xrpl-py/pull/490

2022-12-12 22:51 UTC, connorjchen reviewed
^

2022-12-12 22:58 UTC, closed without merging