feat: make `autofill_transaction` a public method
XRPLF/xrpl-py pull request #331
Opened 2021-12-11 01:11 UTC by mvadari

## High Level Overview of Change

This PR makes `_autofill_transaction` into a public method `autofill_transaction`. This exposes it to library users.

### Context of Change

Requested by @mDuo13 because there is only a sign-and-autofill public method, not just an autofill method.

### Type of Change

- [x] New feature (non-breaking change which adds functionality)

## Before / After

## Test Plan

CI passes. Adjusted a few tests to call `autofill_transaction` directly instead of sign-and-autofill.

2021-12-13 19:34 UTC, mDuo13 requested changes
Haven't tried it yet, but the general idea looks right. But, I suggest naming it just `autofill`.

2021-12-14 18:51 UTC, khancode approved these changes
LGTM. I agree with Rome to rename it to just `autofill`

2021-12-15 18:51 UTC, mvadari commented
> But, I suggest naming it just autofill.
@mDuo13 I wanted to keep the naming consistent with everything else here. I agree that renames are needed, but that can happen in a separate PR.

2021-12-15 20:26 UTC, mDuo13 commented
> I agree that renames are needed, but that can happen in a separate PR.

I disagree about doing it in a separate PR. I don't think it's wise to introduce a new public method, even if only temporarily/pre-release, if the plan is to change its name anyway. Better to get the name right the first time.

2021-12-16 22:49 UTC, intelliot commented on CHANGELOG.md
> +- Makes `autofill` a publicly exposed method
```suggestion
- `autofill`, a new public method that populates the `fee`, `sequence`, and `last_ledger_sequence` fields of a transaction, based on the current state retrieved from the server the Client is connected to. It also converts all X-Addresses to classic addresses.
```

- Most users probably weren't aware that there was a private autofill method before
- This matches the grammar of other lines (e.g. "`xrpl.utils.str_to_hex` and `xrpl.utils.hex_to_str` helpers") and reads naturally off of "Added", as in: Added `autofill`, a new public method…

2021-12-17 21:20 UTC, JST5000 commented on tests/integration/sugar/test_transaction.py
> +        payment_signed = await autofill(payment, client)
This no longer is signed, should `payment_signed` be renamed? (Or is this supposed to be signed still?

2021-12-17 21:30 UTC, ledhed2222 approved these changes

2021-12-17 22:55 UTC, merged