rename XLS-20 fields
XRPLF/xrpl-py pull request #375
Opened 2022-04-19 19:02 UTC by khancode

## High Level Overview of Change

Rename XLS-20 fields to match rippled v1.9.0. https://github.com/XRPLF/xrpl.js/issues/1965

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (non-breaking change that only restructures code)
- [x] Release

## Test Plan

All tests pass.

2022-04-19 20:53 UTC, ckniffen requested changes

2022-04-19 20:53 UTC, ckniffen commented on xrpl/models/requests/nft_buy_offers.py
> +    nf_token_id: str = REQUIRED  # type: ignore
This should be `nft_id`.

2022-04-19 20:53 UTC, ckniffen commented on xrpl/models/requests/nft_sell_offers.py
> +    nf_token_id: str = REQUIRED  # type: ignore
This should be `nft_id`

2022-04-19 21:30 UTC, ckniffen approved these changes

2022-04-20 20:30 UTC, ledhed2222 approved these changes

2022-04-21 21:57 UTC, JST5000 approved these changes
LGTM :)

2022-04-22 20:25 UTC, merged