Create escrow_utility.py
XRPLF/xrpl-py pull request #387
Opened 2022-05-11 16:02 UTC by ObiajuluM

I added a method for generating crypto conditions for escrows.

2022-05-11 16:06 UTC, mvadari commented on xrpl/utils/escrow_utility.py
> +from cryptoconditions import PreimageSha256
This needs to be added to `poetry`

2022-05-11 16:08 UTC, mvadari requested changes
You should add tests and run the linter. Details on how to operate in this repo are in `CONTRIBUTING.md`

2022-05-11 16:47 UTC, ObiajuluM commented
> You should add tests and run the linter. Details on how to operate in this repo are in `CONTRIBUTING.md`

I'm sorry, I don't know how to do all that. maybe you could add the method as your own commit. thanks

2022-05-11 17:42 UTC, khancode commented
> > You should add tests and run the linter. Details on how to operate in this repo are in `CONTRIBUTING.md`
> 
> I'm sorry, I don't know how to do all that. maybe you could add the method as your own commit. thanks

@ObiajuluM We're not prioritizing this change. However, if you want this feature soon then you can do it.

2022-05-11 18:49 UTC, ObiajuluM commented
> > > You should add tests and run the linter. Details on how to operate in this repo are in `CONTRIBUTING.md`
> > 
> > 
> > I'm sorry, I don't know how to do all that. maybe you could add the method as your own commit. thanks
> 
> @ObiajuluM We're not prioritizing this change. However, if you want this feature soon then you can do it.

Noted.

2022-05-12 00:28 UTC, ObiajuluM commented
Hello, I created a gist for the method its lightweight and should be treated as optional, you can find it [here](https://gist.github.com/ObiajuluM/8da69c628879161c019a9256aa168d65), @mvadari i made the change from dict to TypedDict.
thanks

2022-05-12 00:28 UTC, closed without merging