added ticket_sequence to Transaction class common fields
XRPLF/xrpl-py pull request #428
Opened 2022-08-30 18:53 UTC by connorjchen

## High Level Overview of Change

Added ticket_sequence field to common Transaction class fields

### Context of Change

Based on issue "Add common field ticket_sequence to Transaction #413" 

### Type of Change

- [ ] New feature (non-breaking change which adds functionality)

## Test Plan

Passes linter

## TODO

Should write unit test for this change
Untested -> Should run unit & integration tests
Generate docs? Update definitions? Release edits?

2022-08-30 21:22 UTC, mvadari commented
nit: this PR should have a name somewhat akin to https://www.conventionalcommits.org/en/v1.0.0/ (see: other PRs)

2022-08-31 20:13 UTC, JST5000 commented on tests/unit/models/transactions/test_transaction.py
> +    def test_to_dict_ticket_sequence_with_sequence_zero(self):
Basic intent with this suggestion is to make it really obvious to future readers exactly what this test should do, especially if they have no context on why this test exists. 
```suggestion
    def test_throws_when_ticket_sequence_and_sequence_both_non_zero(self):
```

2022-08-31 20:17 UTC, JST5000 commented on tests/unit/models/transactions/test_transaction.py
> +    def test_ticket_sequence_with_sequence_nonzero(self):
Basic intent with this suggestion is to make it really obvious to future readers exactly what this test should do, especially if they have no context on why this test exists. 
```suggestion
    def test_throws_when_ticket_sequence_and_sequence_both_non_zero(self):
```

2022-08-31 20:17 UTC, JST5000 commented on tests/unit/models/transactions/test_transaction.py
> +    def test_ticket_sequence_with_sequence_nonzero(self):
(Initially made the comment on the wrong test case)

2022-08-31 20:17 UTC, JST5000 commented on tests/unit/models/transactions/test_transaction.py
> +    def test_ticket_sequence_with_account_txn_id(self):
ditto - this is a bit vague about what the expected outcome should be.

2022-08-31 20:20 UTC, JST5000 commented on xrpl/models/transactions/transaction.py
> +        if(self.ticket_sequence is not None and (self.sequence is not None and self.sequence != 0 or self.account_txn_id is not None)):
I would add an extra pair of parenthesis just to really clarify the order of operations here.
```suggestion
        if(self.ticket_sequence is not None and ((self.sequence is not None and self.sequence != 0) or self.account_txn_id is not None)):
```

2022-08-31 20:20 UTC, JST5000 commented on xrpl/models/transactions/transaction.py
> +            errors["Transaction"] = "If ticket sequence provided, account_txn_id must be None and sequence must be None or 0"
nit to keep things consistent
```suggestion
            errors["Transaction"] = "If ticket_sequence provided, account_txn_id must be None and sequence must be None or 0"
```

2022-08-31 21:32 UTC, JST5000 approved these changes
LGTM

2022-09-01 00:16 UTC, ckniffen approved these changes

2022-09-01 16:18 UTC, JST5000 requested changes
Oh, could you actually also add this as an entry in HISTORY.md?

2022-09-01 18:44 UTC, intelliot approved these changes

2022-09-01 18:44 UTC, intelliot commented on CHANGELOG.md
> +- Common field ticket_sequence to Transaction class
```suggestion
- Common field `ticket_sequence` to Transaction class
```

2022-09-01 18:44 UTC, intelliot commented on xrpl/models/transactions/transaction.py
> +    this is provided, Sequence must be 0. Cannot be used with account_txn_id.
```suggestion
    this is provided, sequence must be 0. Cannot be used with account_txn_id.
```

2022-09-01 18:45 UTC, intelliot commented
Maybe consider adding a link to https://xrpl.org/tickets.html somewhere in here? Just a thought

2022-09-01 19:01 UTC, merged